# Generated by Django 5.2.12 on 2026-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("book_id", models.IntegerField(unique=True)),
                ("available_qty", models.IntegerField(default=0)),
                ("reserved_qty", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saga_id", models.CharField(max_length=100)),
                ("order_id", models.IntegerField()),
                ("book_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(choices=[("RESERVED", "Reserved"), ("COMMITTED", "Committed"), ("RELEASED", "Released")], default="RESERVED", max_length=20)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("saga_id", "book_id"), name="uniq_inventory_reservation"),
                ],
            },
        ),
    ]
