from django.contrib import admin
from django.urls import path

from app.views import (
    book_detail_api, books_api, books_ui, cart_by_customer_api,
    cart_item_detail_api, cart_items_api, cart_ui, carts_api,
    categories_api, categories_ui, customer_orders_api, customers_api,
    customers_ui, home_ui, managers_api, managers_ui, orders_api,
    orders_ui, payments_api, payments_by_order_api, payments_ui,
    recommendations_api, recommendations_ui, reviews_api,
    reviews_by_book_api, reviews_ui, shipments_api,
    shipments_by_order_api, shipments_ui, staff_book_detail_api,
    staff_books_api, staff_delete_book_ui, staff_ui,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/books/", books_api),
    path("api/books/<int:book_id>/", book_detail_api),
    path("api/customers/", customers_api),
    path("api/carts/", carts_api),
    path("api/carts/<int:customer_id>/", cart_by_customer_api),
    path("api/cart-items/", cart_items_api),
    path("api/cart-items/<int:item_id>/", cart_item_detail_api),
    path("api/orders/", orders_api),
    path("api/orders/<int:customer_id>/", customer_orders_api),
    path("api/payments/", payments_api),
    path("api/payments/<int:order_id>/", payments_by_order_api),
    path("api/shipments/", shipments_api),
    path("api/shipments/<int:order_id>/", shipments_by_order_api),
    path("api/reviews/", reviews_api),
    path("api/reviews/book/<int:book_id>/", reviews_by_book_api),
    path("api/managers/", managers_api),
    path("api/categories/", categories_api),
    path("api/staff/books/", staff_books_api),
    path("api/staff/books/<int:book_id>/", staff_book_detail_api),
    path("api/recommendations/", recommendations_api),
    path("", home_ui),
    path("books-ui/", books_ui),
    path("cart-ui/<int:customer_id>/", cart_ui),
    path("orders-ui/<int:customer_id>/", orders_ui),
    path("payments-ui/<int:order_id>/", payments_ui),
    path("reviews-ui/<int:book_id>/", reviews_ui),
    path("managers-ui/", managers_ui),
    path("categories-ui/", categories_ui),
    path("customers-ui/", customers_ui),
    path("shipments-ui/<int:order_id>/", shipments_ui),
    path("recommendations-ui/", recommendations_ui),
    path("staff-ui/", staff_ui),
    path("staff-ui/delete/<int:book_id>/", staff_delete_book_ui),
]
