# Generated by Django 6.0.3 on 2026-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_prompt_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_source',
            field=models.CharField(choices=[('OFFICIAL', 'Official Cover'), ('AI', 'AI Generated'), ('PLACEHOLDER', 'Placeholder')], default='PLACEHOLDER', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='image_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='official_cover_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='official_cover_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='official_cover_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
